DO-1311 Cluster autoscaler exporter
bringg/caexporter pull request #1
Opened 2021-12-01 15:11 UTC by Dadavan

2021-12-01 17:08 UTC, shamil reviewed
Looks fine, and I'm ok to merge it as is, but if you want to know some best practicies of good exporter, read the points below

1. When using `collector` patter, it is desired to use `const` metrics (`prometheus.NewConstMetric`)
2. Have a global `namespace` for the metrics
3. Have an `init` function that collects `version` metrics, like
```go
const namespace = "cluster_autoscaler"

func init() {
	prometheus.MustRegister(version.NewCollector(namespace))
}
```
4. Use `promu` to build the exporter
5. put `collector` in separate file
6. add locking, so if collector runs, other process will wait for it to finish, to avoid multiple calls to kubernetes API

Recommend to read a simple guide about collector pattern: https://blog.callr.tech/kamailio-exporter-for-prometheus/ 

Also see one I've built a while ago as a reference: https://github.com/shamil/s3-bucket-permissions-exporter

2021-12-01 17:08 UTC, shamil commented on caexporter.go
> +func main() {
missing some minimal flags management like `web.listen-address` and `web.telemetry-path`

2021-12-01 17:08 UTC, shamil commented on caexporter.go
> +	lastActivity.Describe(ch)
```suggestion
	prometheus.DescribeByCollect(c, ch)
```

2021-12-01 17:08 UTC, shamil commented on caexporter.go
> +	up = prometheus.NewGauge(prometheus.GaugeOpts{
this doesn't make sense. usually `up` metrics is not for exporter, but for the collected target.
for the cases where exporter is down/up, prometheus will have the `up` metric [automatically](https://prometheus.io/docs/concepts/jobs_instances/#automatically-generated-labels-and-time-series)

2021-12-01 19:25 UTC, shamil commented on caexporter.go
> +	cm, err := c.kubeClient.CoreV1().ConfigMaps("kube-system").Get(context.TODO(), "cluster-autoscaler-status", metav1.GetOptions{})
I would use `context.WithTimeout` to avoud request hanging

2021-12-01 19:27 UTC, shamil commented on caexporter.go
> +		log.Fatal().Err(err)
You should not use `Fatal` or `panic` once process started, you should just log `error` and retry in next iteration

2021-12-01 19:28 UTC, shamil commented on go.mod
> +go 1.16
migrate to `1.17` they have `gomod` imrpvements there

2021-12-01 19:31 UTC, shamil commented on go.mod
> +module caexporter
```suggestion
module github.com/bringg/caexporter
```

2021-12-01 19:33 UTC, shamil commented on caexporter.go
> +	r.MustRegister(newCollector())
```suggestion
	prometheus.MustRegister(newCollector())
```

2021-12-01 19:36 UTC, shamil commented on caexporter.go
> +	http.Handle("/metrics", promhttp.HandlerFor(r, promhttp.HandlerOpts{}))
```suggestion
	http.Handle("/metrics", promhttp.Handler())
```

Add also handler for root `/` which print the info about `/metrics` path

2021-12-05 15:05 UTC, shamil requested changes
Much better!

I would also recommend managing logs and flags using what is recommended by prometheus (e.g promlog and kingpin), but this is not blocker at all IMO. Added some small comments and we are good to go.

2021-12-05 15:05 UTC, shamil commented on README.md
> +A Prometheus Exporter for reporting the last activity of the Kubernetes Cluster Autoscaler, gathered from the CAS config map.
I think you should mention that this exporter is needed only on k8s clusters that doesn't directly expose the `CAS` metrcis, such as GKE, otherwsie scraping `CAS` metrics directly will have same metric already exposed

2021-12-05 15:05 UTC, shamil commented on caexporter.go
> +	prometheus.MustRegister(version.NewCollector(namespace))
using it as is won't produce useful exporter info metric, it will look like 

```
cluster_autoscaler_build_info{branch="",goversion="go1.17.2",revision="",version=""} 1
```

`revision` and `version` are empty.


So, if you don't need any reviosn/version information exposed, then remove this. If you do then use `ldflags` during build iun the `Dockefile` to specify those.

like 

```
go build -ldflags="-X github.com/prometheus/common/version.Version=0.0.1 -X github.com/prometheus/common/version.Revision=$(git rev-parse HEAD)" ./
```

2021-12-05 15:05 UTC, shamil commented on caexporter.go
> +		log.Err(err)
you should return here

2021-12-05 15:05 UTC, shamil commented on caexporter.go
> +			log.Err(err)
you should return here

2021-12-05 15:05 UTC, shamil commented on caexporter.go
> +		activityTime, err := time.Parse(layout, val)
no need to set date format each time, so put it outside of the loop, or just use the string directly like:

```suggestion
		activityTime, err := time.Parse("2006-01-02 15:04:05 -0700 MST", val)
```

2021-12-05 19:07 UTC, shamil approved these changes

2021-12-06 06:15 UTC, HagaiBarel requested changes

2021-12-06 06:15 UTC, HagaiBarel commented on caexporter.go
> +		log.Err(err)
Use log level here, e.g:
```suggestion
		log.Error().Err(err).Msg("")
```

2021-12-06 06:15 UTC, HagaiBarel commented on caexporter.go
> +			log.Err(err)
Use log level, see above

2021-12-06 06:15 UTC, HagaiBarel commented on caexporter.go
> +			log.Err(err)
Use log level, see above

2021-12-06 06:15 UTC, HagaiBarel commented on caexporter.go
> +	log.Fatal().Err(http.ListenAndServe(*webListenAddress, nil))
```suggestion
	log.Fatal().Err(http.ListenAndServe(*webListenAddress, nil)).Msg("")
```

You have to call `Msg` in order to send the event

2021-12-06 09:42 UTC, HagaiBarel approved these changes

2021-12-06 10:35 UTC, merged