BRNGG-38927 switch from regex to yaml unmarshaling and upgrade deps
bringg/caexporter pull request #17
Opened 2024-12-05 10:00 UTC by Dadavan

2024-12-05 21:33 UTC, shamil requested changes

2024-12-05 21:33 UTC, shamil commented on Makefile
> +VERSION := 0.0.5
since this is breaking change I would increase the version to`1.0.0`

2024-12-05 21:33 UTC, shamil commented on caexporter.go
>  	}
```suggestion
	
	if err := yaml.Unmarshal([]byte(cmData), &status); err != nil {
		log.Info().Msg("Failed to unmarshal YAML data")
		log.Debug().Msgf("Received configmap status %s", cmData)
		return
	}
```

2024-12-05 21:33 UTC, shamil commented on caexporter.go
> -		scrapeError.Set(1)
I think we should keep the scrape error metric

2024-12-08 16:41 UTC, shamil approved these changes

2024-12-09 09:46 UTC, Rachunc approved these changes

2024-12-09 09:46 UTC, merged